### ISSUE TITLE
Adding CheckComboBox (ControlsFX) as a column filter type

### ISSUE THREAD

**Issue by clisztian** [Evgen2sat/JFXTableView#11]
Greetings, 
This is a fantastic addition to the javafx community. I really love using this. I was wondering how feasible it would be to add an additional column filtering type (on Strings) using a CheckComboBox (org.controlsfx) to select a variety of String values typically used as categories. 
Thanks for considering. Cheers

**Comment by Evgen2sat** [comment]
Hello. Great idea. Unfortunately, there is no way to start implementing new features yet, but I promise that I will add this feature.

**Comment by clisztian** [comment]
Great, thanks a lot for the feedback

**Comment by Evgen2sat** [comment]
Hello. At the moment there is a similar implementation (not with CheckComboBox). Click on the filter icon [screenshot_1](https://a.radikal.ru/a23/2202/14/43243b60c708.jpg), select "Setting filtering" [screenshot_2](https://a.radikal.ru/a05/2202/95/e521d4fdd894.jpg), select "For any options" [screenshot_3](https://b.radikal.ru/b40/2202/16/534467835299.jpg). After that, the rows will be filtered by the selected values with an OR comparison

**Comment by clisztian** [comment]
Yep, this works great for me. Thanks
