### ISSUE TITLE
Option to hide first column

### ISSUE THREAD

**Issue by georgemoralis** [Evgen2sat/JFXTableView#2]
I haven't find anything like this maybe i miss something . It might be useful to be able to hide it in case you don't want numbered lines

**Comment by Evgen2sat** [comment]
At the moment it is not possible. Will be implemented later.

**Comment by Evgen2sat** [comment]
release in https://github.com/Evgen2sat/JFXTableView/releases/tag/1.0.3.0
use jfxTableView.setVisibleNumberedRowsColumn();
