### ISSUE TITLE
Equal BigDecimals is wrong

### ISSUE THREAD

**Issue by georgemoralis** [Evgen2sat/JFXTableView#3]
Equal bigdecimal is wrong according to article

https://blogs.oracle.com/javamagazine/four-common-pitfalls-of-the-bigdecimal-class-and-how-to-avoid-them

BigDecimal x = new BigDecimal("1");
BigDecimal y = new BigDecimal("1.0");
System.out.println(x.equals(y));

The console output is the following:

False

This output is due to the fact that a BigDecimal consists of an unscaled integer value with arbitrary precision and a 32-bit integer scale, both of which must be equal to the corresponding values of the other BigDecimal that’s being compared. In this case

    x has an unscaled value of 1 and a scale of 0.
    y has an unscaled value of 10 and a scale of 1.

Hence, x is not equal to y.

So x.compareTo(y) == 0  instead of equal should be more proper

**Comment by Evgen2sat** [comment]
thanks, i will fix this error shortly

**Comment by Evgen2sat** [comment]
I'm fixed it in https://github.com/Evgen2sat/JFXTableView/releases/tag/1.0.2.4
